package net.dadamalda.create_compatible_storage.sounds;

public enum MountedStorageSound {
    UNKNOWN, SILENT, BARREL, SHULKER_BOX, CHEST,
    SD_CABINET_VARIANT,
    FR_DRAWER, FR_KITCHEN_DRAWER, FR_STORAGE_CABINET, FR_CRATE, FR_COOLER,
    WW_CLOSET,
    AC_METAL_BARREL,
    LDV_CABINET, LDV_DRAWER, LDV_STORAGE_POT,
    LDBP_PALM_CABINET,
    LDBA_CABINET, LDBA_DRAWER,
    LDBR_CABINET, LDBR_DRAWER,
    LDM_SHELF,
    LDCL_CABINET, LDCL_DRAWER,
    LDF_CABINET, LDF_COFFER
}
