org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
neo_version=21.1.253
create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67

mod_id=create_trains_interactive
mod_name=Create: Trains Interactive
mod_version=1.1.0
mod_group_id=com.nitricacid.traininteractive
mod_authors=NitricAcid; original storage by Dadamalda
mod_description=Use storage, furniture, bar and kitchen blocks and Pick Block on Create trains, with Kaleidoscope Tavern, World Liquor and Farmer's Delight compatibility.
