plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.147'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

repositories {
    mavenCentral()
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
    }
}

neoForge {
    version = neo_version

    runs {
        client {
            client()
            gameDirectory = project.file('runs/client')
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    implementation "maven.modrinth:yacl:${yacl_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            neo_version            : neo_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}

// Deploy the finished mod directly to the user's Modrinth profile after a successful build.
tasks.named('build') {
    doLast {
        copy {
            from tasks.named('jar')
            into file('C:/Users/Tommy/AppData/Roaming/ModrinthApp/profiles/Create Engineer/mods')
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = mod_id
            from components.java
        }
    }
    repositories {
        maven {
            name = 'ProjectLocal'
            url = 'file://' + System.getenv('LOCAL_MAVEN')
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = false
    }
}
