# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.12.101-hotspot
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.248
neo_version_range=[21.1.228,)
loader_version_range=[1,)

create_version=6.0.10-280
create_version_range=[6.0.7,6.1.0)
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67

createaddition_project=439890
createaddition_file_id=8887653

#read more on this at https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Mod Properties
mod_id=createfactorytweaks
mod_name=Create: Factory Tweaks
mod_license=All Rights Reserved
mod_version=1.1.5
mod_group_id=com.nitricacid.createfactorytweaks
mod_authors=NitricAcid
mod_description=Adjustable blaze burner fuels and distillation outputs for Create and TFMG.
